const tasksDom = document.querySelector('.tasks')
const loadingDom = document.querySelector('.loading-text')
const formDom = document.querySelector('.task-form')
const taskInputDom = document.querySelector('.task-input')
const formAlertDom = document.querySelector('.form-alert')